<a href="https://colab.research.google.com/github/Valeria379/PROA/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D0%9F%D0%A0%D0%9E%D0%90_%E2%84%961.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.1

Считайте число n. Создайте в переменной Z Numpy вектор из нулей длины n

In [ ]:
import numpy as np

In [ ]:
Z = np.zeros(5)
print(Z)

[0. 0. 0. 0. 0.]


1.2.

 Посчитайте размер матрицы Z в байтах и выведите его на печать. 


In [ ]:
Z = np.zeros((10,10))
print(Z.nbytes)


800


In [ ]:
Z = np.array([1, 2, 3,], dtype=np.float64)
print(Z.nbytes) 

24


1.3.

 Считайте 2 числа:

n - размер Numpy вектора

x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора
должны быть равны 0. Сохраните вектор в переменную Z.

In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


1.4.

 Считайте 2 числа n, m. Создайте вектор Z состоящий из чисел от n до m с шагом 1

In [ ]:
Z = np.arange(10, 51, 1)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


1.5.

 Дан вектор Z. "Разверните" его.

In [ ]:
Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
print(Z)

[4 3 2 1]


1.6.

 Считайте 3 числа:

n - количество элементов матрицы

m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).
Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется
пустых мест.

In [ ]:
Z = np.arange(6).reshape(2,3)
print(Z)


[[0 1 2]
 [3 4 5]]


In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


1.7.

 Дан вектор Z. Запишите в переменную NonZerros индексы ненулевых элементов

In [ ]:
nz = np.nonzero([1, 0, 2, 0, 3, 0, 4])
print(nz)

(array([0, 2, 4, 6]),)


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4]),)


1.8. 

Считайте число n. Создайте единичную матрицу размера n, сохраните результат в
переменную Z.

In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.9 

Считайте 3 числа: n, m, l.. Зафиксируйте значение генератора случайных чисел Numpy
с помощью numpy.random.seed(42) . Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и
сохраните результат в переменную Z.

In [ ]:
Z = np.random.random((2,2,2))
print(Z)

[[[0.28262404 0.50929062]
  [0.06905183 0.32949406]]

 [[0.68934347 0.75715038]
  [0.46383945 0.93567374]]]


1.10.

 Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с
помощью numpy.random.seed(42). Создайте матрицу n*m из случайных чисел (от 0 до 1). Выведите на печать значение минимального и максимального чисел в получившейся
матрице (каждое с новой строки).

In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin)
print(Zmax)

0.004510622052267821
0.9830656633921308


In [ ]:
Z = np.random.random((2,6))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin)
print(Zmax)

0.0104018331049186
0.7021868779853558


1.11.

 Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с
помощью numpy.random.seed(42).Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение среднего для всей матрицы.

In [ ]:
Z = np.random.random((30, 30))
m = Z.mean()
print(m)

0.5098199667918688


In [ ]:
Z = np.random.random((12, 6))
m = Z.mean()
print(m)

0.5363067590099326


1.12.

 Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и
сохраните в переменную Z.
A и B могут содержать как int, так и float.


In [ ]:
A = np.array([1.5, 2.5, 3.5])
B = np.array([4, 5, 6])
print(np.dot(A, B))

39.5


In [ ]:
A = np.array([1, 3, 5, 7, 9])
B = np.array([-2, 4, -6, 8, -10])
print(np.dot(A, B))

-54


1.13.

 Даны 2 матрицы: A и B. Найдите произведение матриц и сохраните его в переменную Z.
Если найти произведение матриц невозможно, то запишите в Z строку:
Упс! Что-то пошло не так...

In [ ]:
A = np.array([
 [1, 2, 3],
 [4, 5, 6]
])
B = np.array([
 [11.5],
 [12.5],
 [13.5]
])
Z = np.dot(A, B)
print(Z)

[[ 77. ]
 [189.5]]


In [ ]:
A = np.array([
 [1, 2, 3],
 [4, 5, 6]
])
B = np.array([
 [11.5, 12.5, 13.5]
])
print("Упс, что-то пошло не так...")

Упс, что-то пошло не так...


1.14.

 Поменяйте знак всех чисел из интервала (3; 9), хранящихся в векторе Z.

In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 9)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
Z = np.array([-10, -5, 0, 5, 10])
Z[(10 < Z) & (Z < 5)] *= 0
print(Z)

[-10  -5   0   5  10]


1.15.

Подсчитать произведение ненулевых элементов на диагонали прямоугольной
матрицы. Для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [ ]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(np.prod(np.diag(X)[np.diag(X)!=0]))

3


In [ ]:
import numpy as np

1.16. Считайте число n. Создайте в переменной Z Numpy вектор из нулей длины n.

In [ ]:
Z = [0, 0, 0, 0, 0] 
vtr = np.array(Z) 
print(Z) 

[0, 0, 0, 0, 0]


1.17. Посчитайте размер матрицы Z в байтах и выведите его на печать. Чтобы узнать
размер (в байтах) 1 элемента матрицы используйте

In [ ]:
Z = np.zeros((10,10))
print(Z.nbytes)


800


1.18. Считайте 2 числа:

n - размер Numpy вектора

x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора
должны быть равны 0. Сохраните вектор в переменную Z.


In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


1.19. Считайте 2 числа n, m. Создайте вектор Z состоящий из чисел от n до m с шагом 1

In [ ]:
Z = np.arange(10:50)
print(Z)

1.20. Дан вектор Z. "Разверните" его.

In [ ]:
Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
print(Z)

[4 3 2 1]


1.21. Считайте 3 числа:

n - количество элементов матрицы

 m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).

In [ ]:
Z = np.arange(6).reshape(2,3)
print(Z)

[[0 1 2]
 [3 4 5]]


In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


1.22. Дан вектор Z. Запишите в переменную NonZerros индексы ненулевых элементов.

In [ ]:
nz = np.nonzero([1, 0, 2, 0, 3, 0, 4])
print(nz)

(array([0, 2, 4, 6]),)


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


1.23. Считайте число n. Создайте единичную матрицу размера n, сохраните результат в
переменную Z.

In [ ]:
n = int(input("Введите число: "))
for i in range(0, n):
    for j in range(0, n):
        if(i == j):
            print("1", sep=" ", end=" ")
        else:
            print("0")


Введите число: 3
1 0
0
0
1 0
0
0
1 

1.24. Считайте 3 числа: n, m, l.. Зафиксируйте значение генератора случайных чисел
Numpy с помощью numpy.random.seed(42) . Создайте матрицу n*m*l из случайных чисел (от 0
до 1) и сохраните результат в переменную Z.*Курсив*

In [ ]:
np.random.seed(42)

In [ ]:
np.random.uniform(low=0, high=1, size=(4, 2))

array([[0.96631751, 0.02028441],
       [0.54011973, 0.70646375],
       [0.31274233, 0.18761267],
       [0.3943358 , 0.39312143]])

1.25. Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с
помощью numpy.random.seed(42). Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение минимального и максимального чисел в получившейся
матрице (каждое с новой строки).

In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin)
print(Zmax)

0.006308827066095146
0.9958893328576237


In [ ]:
Z = np.random.random((2,6))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin)
print(Zmax)

0.02708519076382898
0.9117256399330264
